# ========== AUTH SERVICE - SERVICIO DE AUTENTICACION ==========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: publicaciones-system
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: josue122121/authservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          env:
            # Spring Application
            - name: SPRING_APPLICATION_NAME
              value: "SERVICIO-AUTENTICACION"
            - name: SERVER_PORT
              value: "8081"

            # Database Configuration
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-auth:5432/authservice_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgreSQLDialect"

            # Eureka Configuration
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka-url
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "${SPRING_APPLICATION_NAME}:${HOSTNAME}"

            # JWT Configuration
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: jwt-secret
            - name: JWT_EXPIRATIONMS
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: jwt-expiration

            # Management and Logging
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: "INFO"

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: publicaciones-system
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP