# ========== API GATEWAY - PUNTO DE ENTRADA ==========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: publicaciones-system
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: josue122121/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            # Spring Application
            - name: SPRING_APPLICATION_NAME
              value: "API-GATEWAY"
            - name: SERVER_PORT
              value: "8000"

            # Spring Cloud Gateway Configuration
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
              value: "true"

            # Eureka Configuration
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka-url
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "${SPRING_APPLICATION_NAME}:${HOSTNAME}"

            # JWT Configuration
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: jwt-secret
            - name: JWT_EXPIRATIONMS
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: jwt-expiration

            # Management
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: publicaciones-system
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP