# ========== PUBLICACIONES SERVICE - SERVICIO PRINCIPAL ==========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicaciones-service
  namespace: publicaciones-system
  labels:
    app: publicaciones-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publicaciones-service
  template:
    metadata:
      labels:
        app: publicaciones-service
    spec:
      containers:
        - name: publicaciones-service
          image: josue122121/ms-publicaciones:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            # Spring Application
            - name: SPRING_APPLICATION_NAME
              value: "SERVICIO-PUBLICACIONES"
            - name: SERVER_PORT
              value: "8080"

            # Database Configuration
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-publicaciones:5432/db-publicaciones"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS
              value: "true"

            # RabbitMQ Configuration
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: rabbitmq-host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: rabbitmq-port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password

            # Eureka Configuration
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: eureka-url
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "${SPRING_APPLICATION_NAME}:${HOSTNAME}"

            # Management
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: publicaciones-service
  namespace: publicaciones-system
  labels:
    app: publicaciones-service
spec:
  selector:
    app: publicaciones-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP